### ISSUE TITLE
erc20 to erc20 issue `fixAssetsAboveLimits`

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/poa-bridge-contracts#244]
Scenario:
1. Deploy erc20 to erc20 bridge
2. Setup equal limits on Home and Foreign Side
3. Make a transfer that exceeds MAX_AMOUNT_PER_TX
4. Call `fixAssetsAboveLImits` by owner
Result:
It makes validators to call `executeSignatures` and it still checks for `withinLimits` 
The purpose of the func is `fixAssetsAboveLImits` which doesn't actually work what is intended to do

**Comment by akolotov** [comment]
@patitonar please take a look

**Comment by patitonar** [comment]
On the described scenario when `fixAssetsAboveLImits` is called with `unlockOnForeign` param set to `true` it will emit the event `UserRequestForSignature`.

After the validators process the event, they will call `executeSignatures` on foreign and it check that the value is `withinExecutionLimit`, which is not, and the transaction will fail.

The emitted event `UserRequestForSignature` can not be distinguish from the others emitted on regular transfers from Home to Foreign, that's why it also check for the limits. And if it could, this limit is in place for controlling possible validator's misbehaviour so I don't know if it makes sense to avoid this check.

Since `fixAssetsAboveLImits` is a special invocation by the owner it makes sense to be responsibility of the owner to previously check that limits will allow the transaction to success.

In this case, to be able to return the locked assets the owner will need to first update `executionMaxPerTx` and/or `executionDailyLimit` if needed on foreign side. It's not the ideal solution, but I don't see a clear workaround for this.

Any other thoughts @akolotov ?

**Comment by akolotov** [comment]
@patitonar thank for detailed answer.

First of all, the owners of the bridge should follow the following logic:
* `executionMaxPerTx` on the Foreign side should be equal to `maxPerTx` on the Home side
* `executionDailyLimit` on the Foreign side should be equal to `dailyLimit` on the Home side

at least such logic is implemented in the deployment scripts:
https://github.com/poanetwork/poa-bridge-contracts/blob/b66a678648ea89b6441382c7a7adefb3b0b02667/deploy/src/erc_to_erc/foreign.js#L76-L87

Next, there are three different possible cases when `fixAssetsAboveLimits` is called.
1. `txHash` refers to a transaction with the value less or equal than the parameter `executionMaxPerTx` on the Foreign side. Such call will unlock the tokens successfully.
2. `txHash` refers to a transaction with the value greater than `executionMaxPerTx` but less or equal than the parameter `executionDailyLimit` on the Foreign side. This call will cause failure of token unlocking on the Foreign side.
3. `txHash` refers to a transaction with the value greater than `executionDailyLimit` on the Foreign side. This call will cause failure of token unlocking on the Foreign side as well.

Based on the facts listed above, it seems logical
1. to revert the call of `fixAssetsAboveLImits` if the value to relay is greater than `maxPerTx`.
2. to allow to specify the caller exact value to be relayed as additional parameter of `fixAssetsAboveLimits`. By doing this the functionality of the method should be changed to keep amount tokens appeared due to the specific `txHash` but not relayed yet. Every call of `fixAssetsAboveLimits` with the corresponding `txHash` will reduce this amount with the value specified in the call.

In this case the owners could unlock tokens in several calls. If the value of tokens that is going to be unlocked pretends to become greater than `dailyLimit`, the user should send the next unlocking call after 24 hours.

What do you think about this suggestion?

**Comment by rstormsf** [comment]
I think the problem is in architecture. If approve + transferFrom is used, then you won't have these kind of problems since you can check before send

**Comment by akolotov** [comment]
@rstormsf thanks, we will do this for sure. 
But we cannot postpone this particular release due to this bug. That's why I would provide the workaround like described above.

**Comment by akolotov** [comment]
Included in [TokenBridge contracts 2.4.0](https://github.com/poanetwork/poa-bridge-contracts/releases/tag/2.4.0)
