### ISSUE TITLE
Result of message call for AMB feature

### ISSUE THREAD

**Issue by akolotov** [poanetwork/poa-bridge-contracts#281]
This issue is opened as reflection corollary of the issue described here: https://github.com/poanetwork/poa-bridge-contracts/issues/267#issuecomment-529027876.

The main idea is to provide an ability to properly handle a situation when a message call was failed as part of an attempt to relay it from one chain to another. At this particular moment we just report about the invocation status by the event:

https://github.com/poanetwork/poa-bridge-contracts/blob/9c19ec51ac23d83d44d50a71f63fe01f749547c1/contracts/upgradeable_contracts/arbitrary_message/MessageProcessor.sol#L40-L55

But it is not enough since there is no simple way to have a reliable confirmation that the call causes the fail or success.

It is very undesired to use a scheme when the bridge invokes a call back if the status of the message execution is `false`. The reason is possibility of an attack to dry out the validator balance or spam the bridge. An attacker will generate such relay request so the validators will spend lots of resources to execute the call back.

Below is a proposal to provide reliable information about the message call status:

1. The bridge contract will store the status of every message call by associating it with the originating message hash (or something like this). Eventually we need to have correspondence between an originating call on one side and the result on another side. This information will be available for other contracts.
2. A contract (that uses the bridge) could requests the status of the message call by its hash. After that the contract is able to send a message call on another side of the bridge reporting that the original call was failed. 
3. The contract-receiver gets the confirmation (relayed through the bridge) that the corresponding call was failed and performs actions to recover the unsuccessful relay request. E.g. for the `erc677-to-erc677` bridge the mediator contract could unlock/mint the corresponding number of tokens. And it assumes that the contract mediator (that will be the contract-receiver then) needs to store a correspondence between the relay request and his attributes (the sender and value).

**Comment by patitonar** [comment]
Following the proposal, here is an implementation idea.

The bridge contract for every message will store and expose to other contracts:
- The status of the message call associated to the originating transaction hash.
- The hash of the `data` of the message passed to the call (`keccak256(data)`) associated to the originating transaction hash. To save gas, I think we can consider to only store this for the failed message calls.

Here is an example of how to use the information for `erc677-to-erc677` bridge:

1. Mediator in network A calls `requireToPassMessage` and store `sender` and `value` associated to the hash of the `data` parameter (`keccak256(data)`) used in `requireToPassMessage`.
2. Message execution call fails in network B. The bridge contract stores the status and the hash of the data parameter associated to the tx hash.
3. After detecting that the call failed. The `proxyOwner` of the contract mediator in network B invokes a method with the tx hash that will:
- check that the tx hash was not marked as fixed
- call the bridge to check that the status is failed
- call the bridge to get the associated data hash
- send a message call to the mediator contract in network A with the data hash as parameter
- mark the tx hash as fixed
4. Mediator in network A uses the data hash to get the `sender` and `value` associated and unlock/Mint the tokens.

**Comment by akolotov** [comment]
> send a message call to the mediator contract in network A with the data hash as parameter

we cannot rely on the `data` hash since it is not unique. Let's think of another way.

**Comment by patitonar** [comment]
That's correct, the `data` hash is not unique, I'll think of another approach but do we need to use an unique identifier to bind the relay request to the attributes used? As a unique identifier to operate we have the tx hash. In the example, the data hash will be related always to the same attributes of `sender` and `value` which is OK to use several times if the user sent the same messages to the other network. The tx Hash can be used to avoid fixing twice each of the messages.

**Comment by akolotov** [comment]
the issue with usage of `data` just now is that the `data` for different recipients could be the same. So, if a user `A` generates a transaction with data `D` for the contract receiver `C1` and the relay operation is OK, the same user `A` could call another contract `C2` with the same data `D` assuming that this operation fails - after that I could invoke `C1` and points out the transaction sent to `C2`.

**Comment by akolotov** [comment]
What if we modify you scheme a bit:

The bridge contract for every message will store and expose to other contracts:
  * the status of the message call associated to the originating transaction hash.
  * the hash of `(keccak256(data))` associated to the originating transaction hash. **The contract-sender is responsible for providing unique sequence as part of the `data`**. To save gas, the association is stored only for the failed message calls.
  * **the receiver of the failed message call associated to the originating transaction hash.**

In this case for the `erc677-to-erc677` bridge operations the logic could be as follows:
1. The mediator in the network `A` calls `requireToPassMessage` and stores `sender` and `value` associated to the hash of the data parameter `(keccak256(data))` **where data consist of `abi.encodeWithSelector(methodSelector, from, value, nonce)`. After storing the pair of values `nonce` becomes the hash (`nonce=hash`).**
2. The message execution call fails in the network `B`. The bridge contract stores the status for the originating tx hash.
3. After detecting that the call failed **any user** in the network` B` is able to invoke a method from the mediator contract with the originating tx hash that will:
    * check that the tx hash was not marked as fixed
    * call the bridge to check that the status is failed
    * **call the bridge to check the receiver of the failed tx is this contract itself**
    * call the bridge to get the associated data hash
    * send a message call to the mediator contract in the network `A` with the data hash as parameter
    * mark the tx hash as fixed
4. The mediator in the network `A` uses the data hash to get the sender and value associated and unlock/Mint the tokens.

What do you think?

**Comment by patitonar** [comment]
> the receiver of the failed message call associated to the originating transaction hash.

I think it's a good idea, exposing the receiver of the failed message call solves the problem mentioned in [this comment](https://github.com/poanetwork/poa-bridge-contracts/issues/281#issuecomment-529680101). 
But I think we should also **expose the sender of the failed message call associated to the originating transaction hash.**

There is a scenario where a user generates a call to contract receiver `C1` but not from the paired contract mediator of the other network. So the call could probably fail because of some check like `require(messageSender() == mediatorContractOnOtherSide());`. So in this case the transaction will fail an the user will be able to try to fix it and send the message to the paired contract mediator on the other side. So checking the sender when trying to fix the transaction will help avoid this situation. 

Then step 3. of the example could be updated to:

3. After detecting that the call failed **any user** in the network` B` is able to invoke a method from the mediator contract with the originating tx hash that will:
    * check that the tx hash was not marked as fixed
    * call the bridge to check that the status is failed
    * **call the bridge to check the receiver of the failed tx is this contract itself**
    * **call the bridge to check the sender of the failed tx is the mediator contract on the other side** 
    * call the bridge to get the associated data hash
    * send a message call to the mediator contract in the network `A` with the data hash as parameter
    * mark the tx hash as fixed

> The contract-sender is responsible for providing unique sequence as part of the data

I'm trying to understand if providing a unique sequence is really needed in order to avoid increasing the complexity to the mediator contracts logic. In the example of `erc677-to-erc677` the method that will be called on the other side will need to define in its signature an extra parameter `nonce` that won't be used in the method which will be kind of confusing.

Another idea, still is not a unique sequence but a little bit more customized hash, could be that the bridge will **store the hash of `keccak256(abi.encodePacked(sender, receiver, data))` associated to the originating transaction hash.** So in the example, the `sender` and `value` attributes for the tokens will be associated to the same calculated hash in the mediator that originated the message.

**Comment by akolotov** [comment]
> So checking the sender when trying to fix the transaction will help avoid this situation.

Sorry but probably I did not get the point. 
it is assumed that the data-hash sent by `C2` to fix the transaction and the hash of `abi.encodeWithSelector(methodSelector, from, value, nonce)` is checked by the `C1`. If `nonce` is random enough it is guaranteed that no one could send another transaction with the same data-hash  so `C1` can easily authenticate the fix request.

> that won't be used in the method which will be kind of confusing.

yes, that true. But this is a part of AMB protocol if you want distinguish different relay requests sent from the same contract. 

> still is not a unique sequence but a little bit more customized hash, could be that the bridge will store the hash of `keccak256(abi.encodePacked(sender, receiver, data))` associated to the originating transaction hash. 

If you think that not unique data-hashes are secure enough let's use them. Personally I like the idea that we enlarge gas usage negligible to store `nonce` and increase security significantly.

**Comment by patitonar** [comment]
> Sorry but probably I did not get the point.
it is assumed that the data-hash sent by C2 to fix the transaction and the hash of abi.encodeWithSelector(methodSelector, from, value, nonce) is checked by the C1. If nonce is random enough it is guaranteed that no one could send another transaction with the same data-hash so C1 can easily authenticate the fix request.

Sorry my explanation wasn't very clear.

Using the example of `erc677-to-erc677`. Let's say we have mediator `C1` in network `A` and mediator `C2` in network `B`.
1. A user transfers tokens to `C1` which calls `requireToPassMessage` with data `abi.encodeWithSelector(methodSelector, from, value, nonce)` and stores `from` and `value` related to the hash of the `data`.
2. On `C2` tokens are Minted correctly to the user.
3. Then, since `data` values sent on the transactions are public, the user can copy the `nonce` from explorers, listenting to the events, etc, and then from a different contract `C3` in network `A` can make the exact same invocation as in step `1` using the same `nonce`. Which will generate the same hash of the `data`.
4. On `C2` the transaction will be reverted because of the check `require(messageSender() == mediatorContractOnOtherSide());`.
5. The user will call `C2` to fix the transaction on step `4`. Which passes all the checks: wasn't fixed, status is failed and receiver is `C2`. And will use the data hash that was stored for that transaction which is the same generated in `1`.
6. On `C1` the fix request will find a valid `from` and `value` for the hash provided and Transfer the tokens to the user.

Is this a valid scenario or I am missing something? That's why I suggested to expose the sender of the failed message call associated to the originating transaction hash, to prevent step `5` of succeeding because the sender wasn't the mediator `C1` from the other side.

And this also made me think that probably the following idea helped to have a more secure `hash` to requests between mediators than using a `nonce`:

> Another idea, still is not a unique sequence but a little bit more customized hash, could be that the bridge will store the hash of keccak256(abi.encodePacked(sender, receiver, data)) associated to the originating transaction hash. So in the example, the sender and value attributes for the tokens will be associated to the same calculated hash in the mediator that originated the message.

**Comment by akolotov** [comment]
Ok. Now I see! Thanks for the very explanatory example!

yes, it make sense to keep both the sender and the receiver then.

but from my perspective we need to have `nonce` and here is an example:

1. `C1` sends to `C2` two relay requests with the same data (`receiver + value`). Since they have the same data-hash only one pair of storage words will be responsible for keeping track for these two requests. For the contract `C1` it will look like only one request happened.
2. Both requests are failed. 
3. A user fixes the requests by sending the data-hash to the `C1` on behalf of `C2`.
4. The first message to returns funds should lead to minting/unlocking tokens.
5. Should the second message to return funds lead to minting/unlocking tokens since it has the same data-hash? From my perspective - no - it looks like a replay attack.

Introduction of `nonce` will make sure that with one relay request associated one pair of the storage words (`sender`, `value`). 

What do you think?

**Comment by patitonar** [comment]
> Should the second message to return funds lead to minting/unlocking tokens since it has the same data-hash? From my perspective - no - it looks like a replay attack.

Thanks for the example. I see your point now, with the `nonce` we will be able to prevent replay attacks. So I think we should use it
