### ISSUE TITLE
requiredBlockConfirmations is set by default in zero on Foreign contracts in ERC-TO-ERC mode

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/poa-bridge-contracts#74]
Problem:
when deploying ERC-to-ERC mode, it doesn't apply BlockConfirmations to Foreign Contract

Solution: pass requiredBlockConfirmations to `initialize` method for HomeBridgeErcToErc

**Comment by akolotov** [comment]
Yes, that's real issue. Seems that set of parameters which are accepted by `initialize` of `Foreign` bridge in `native-to-erc20` mode were not moved correctly to the implementation of this method in `erc20-to-erc20` mode:

`native-to-erc20`:
https://github.com/poanetwork/poa-bridge-contracts/blob/2609875974d35873de83001aaf76a8fdbbffdf7e/contracts/upgradeable_contracts/native_to_erc20/ForeignBridgeNativeToErc.sol#L21-L22
`erc20-to-erc20`: 
https://github.com/poanetwork/poa-bridge-contracts/blob/2609875974d35873de83001aaf76a8fdbbffdf7e/contracts/upgradeable_contracts/erc20_to_erc20/ForeignBridgeErcToErc.sol#L14-L16

That's why deployment script does not pass this parameter `FOREIGN_REQUIRED_BLOCK_CONFIRMATIONS` to the Foreign bridge contract:

https://github.com/poanetwork/poa-bridge-contracts/blob/2609875974d35873de83001aaf76a8fdbbffdf7e/deploy/src/erc_to_erc/foreign.js#L120-L121

**Comment by akolotov** [comment]
Addressed in https://github.com/poanetwork/poa-bridge-contracts/pull/71
