### ISSUE TITLE
Warning: Etherscan will show as reverted error

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/poa-bridge-contracts#81]
Since we added optional call if the recepient is contract etherscan will mark it as an error if contract doesn't have a fallback

```solidity
function transfer(address _to, uint256 _value) public returns (bool)
    {
        require(superTransfer(_to, _value));
        if (isContract(_to)) {
            contractFallback(_to, _value, new bytes(0));
        }
        return true;
    }

```

![image](https://user-images.githubusercontent.com/9360827/45727787-0ccd8580-bb7a-11e8-8af5-853f8672042d.png)

You might want to reconsider this. 

This functionality is not used anywhere in production yet, but I just wanted to let you know about it.

Everything is still functioning properly, but I don't think it's good idea to have since many people will just freak out by this error while everything is actually fine.

This will happen if a recepient doesn't have `onTokenTransfer` and then it will call `function fallback` which if not defined will make a `revert()`

**Comment by akolotov** [comment]
Thanks Roman for the report.
Could you clarify more the use case? "Some one would like to transfer tokens to the contract which does not support `onTokenTransfer()`", right?

**Comment by rstormsf** [comment]
@akolotov correct. Imagine just sending to your Multisig wallet and seeing the `revert`ed transaction.
Won't be fun

**Comment by akolotov** [comment]
Hmmm

If an user just does `transfer` of our token to a contract which has no `onTokenTransfer`.
You described the process right that if `onTokenTransfer` does not exists in the contract-receiver of token, `fallback` will `throw`.
But we use `call` to invoke `onTokenTransfer` and it means that the executing method is reverted `call` will get `false` (https://solidity.readthedocs.io/en/v0.4.25/units-and-global-variables.html#address-related) and will this will not cause `revert()`.

https://github.com/poanetwork/poa-bridge-contracts/blob/4e869c0c06dcff4d1d38ca65e9a62e973f5c3e97/contracts/ERC677BridgeToken.sol#L43-L50

https://github.com/poanetwork/poa-bridge-contracts/blob/4e869c0c06dcff4d1d38ca65e9a62e973f5c3e97/contracts/ERC677BridgeToken.sol#L52-L57

If in your case `transfer` is reverted, most probably there is another reason for this rather than absence of  `onTokenTransfer` in the contract-receiver.

**Comment by rstormsf** [comment]
it will. I tried. it will call `revert` opcode, although the tx status will be success...in will be internal `revert` 

Please understand the difference between main thread `revert` where the whole tx fails and where there is internal call where those reverts don't affect the main tx thread.

I'm not sure how else I can explain it

**Comment by rstormsf** [comment]
https://kovan.etherscan.io/tx/0x7e0e2852207d611da10ab90b992167c2ab56914af03d8c4e5ddfe7e50bbe7375

see this example.

Successful erc20 transfer but it's annoying for users to see that something went wrong.
Check Parity trace, you will see a revert opcode.
https://kovan.etherscan.io/vmtrace?txhash=0x7e0e2852207d611da10ab90b992167c2ab56914af03d8c4e5ddfe7e50bbe7375&type=parity

**Comment by akolotov** [comment]
Ok. I see what you mean. For me, it is not the issue with our contracts but the issue with etherscan.

**Comment by rstormsf** [comment]
up to you...as long as you are aware of it.

**Comment by akolotov** [comment]
Closed since there is no issue on the contracts' side.
