### ISSUE TITLE
Calling `transfer` with tokens amount less than *_MIN_AMOUNT_PER_TX works locks tokens 

### ISSUE THREAD

**Issue by akolotov** [poanetwork/poa-bridge-contracts#89]
This scenario is applicable for `native-to-erc` and `erc-to-erc`.

Previously, it was decided to provide users an ability to call `onTokenTransfer()` method automatically even if they use `transfer` instead of `transferAndCall()` to relay assets represented by the Bridgeable ERC677 token.

https://github.com/poanetwork/poa-bridge-contracts/blob/d8e6748a752cfc6c39d63163b26eea87cdb230f7/contracts/ERC677BridgeToken.sol#L47-L54

The `transfer` method tries to call `onTokenTransfer()` similarly to `transferAndCall()` but handle its return value differently: even if the attempt to call `onTokenTransfer()` is failed the tokens will be transferred to recipient successfully.

If we consider the case when the user points out the amount of tokens which is less than the limit configured to specify a minimal amount of tokens possible to transfer in one transaction, `onTokenTransfer()` will be reverted. 

https://github.com/poanetwork/poa-bridge-contracts/blob/d8e6748a752cfc6c39d63163b26eea87cdb230f7/contracts/upgradeable_contracts/ERC677Bridge.sol#L17-L24

https://github.com/poanetwork/poa-bridge-contracts/blob/d8e6748a752cfc6c39d63163b26eea87cdb230f7/contracts/upgradeable_contracts/BasicBridge.sol#L90-L93

It could lead to situation when the tokens are transferred to the bridge account successfully whereas the bridge contract "disagreed" to accept them since the amount of transferred tokens is below the limit. So, instead of relaying assets to another side of the bridge they will be stuck on the bridge account.

**Comment by pertsev** [comment]
We can't just cut `contractFallback` out (due to possible Bridge desynchronization). But the current approach has a couple issues - the first one described above and the second one is Etherscan shows a [red](https://etherscan.io/tx/0xb3874442fdfa8b81a7f8b91ab8fa80717dc60e569dba84446125956d67be6855) message when a recipient is a contract which does not support ERC677. It may confuse users. 

Roughly speaking, we just need to be sure no one can do transfer to the Bridge's contract by `transfer(address _to, uint256 _value)`, so consider implement recipient address check in than function - if it's Bridge than revert tx.

**Comment by akolotov** [comment]
addressed by https://github.com/poanetwork/poa-bridge-contracts/commit/45db0ff5aeae5d5177b0dcc564102314db96ba05
